name: Build PortMidi Library

on:
  push:
    paths:
      - 'Native/portmidi/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows builds
          - os: windows-latest
            rid: win-x64
            platform: Windows
            arch: x64
            cmake_target_arch: x64
          - os: windows-latest
            rid: win-x86
            platform: Windows
            arch: x86
            cmake_target_arch: Win32
          - os: windows-latest
            rid: win-arm64
            platform: Windows
            arch: ARM64
            cmake_target_arch: ARM64

          # Linux builds
          - os: ubuntu-22.04
            rid: linux-x64
            platform: Linux
            arch: x86_64
          - os: ubuntu-22.04
            rid: linux-arm64
            platform: Linux
            arch: aarch64
          - os: ubuntu-22.04
            rid: linux-arm
            platform: Linux
            arch: arm

          # macOS builds
          - os: macos-latest
            rid: osx-x64
            platform: macOS
            arch: x86_64
          - os: macos-latest
            rid: osx-arm64
            platform: macOS
            arch: arm64

    name: Build for ${{ matrix.platform }} - ${{ matrix.arch }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake file binutils lsb-release
          
          # Install Docker for ARM builds
          if [ "${{ matrix.arch }}" == "aarch64" ] || [ "${{ matrix.arch }}" == "arm" ]; then
            sudo apt-get install -y docker.io
            sudo usermod -aG docker $USER || true
          else
            # For native x86_64 build
            sudo apt-get install -y libasound2-dev
          fi

      - name: Build ARM libraries with Docker
        if: runner.os == 'Linux' && (matrix.arch == 'aarch64' || matrix.arch == 'arm')
        run: |
          # Use sudo for Docker commands in CI
          if [ "${{ matrix.arch }}" == "aarch64" ]; then
            DOCKER_ARCH="arm64v8"
          elif [ "${{ matrix.arch }}" == "arm" ]; then
            DOCKER_ARCH="arm32v7"
          fi
          
          sudo docker run --rm -v $PWD:/workspace $DOCKER_ARCH/ubuntu:22.04 /bin/bash -c "
            apt-get update
            apt-get install -y build-essential cmake libasound2-dev
            cd /workspace/Native/portmidi
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_PORTMIDI_TESTS=OFF
            cmake --build build --config Release --parallel
          "
          
          mkdir -p runtimes/${{ matrix.rid }}/native
          cp Native/portmidi/build/libportmidi.so runtimes/${{ matrix.rid }}/native/

      - name: Configure CMake (Non-ARM Linux)
        if: runner.os == 'Linux' && matrix.arch != 'aarch64' && matrix.arch != 'arm'
        shell: bash
        working-directory: Native/portmidi
        run: |
          CMAKE_FLAGS="-DBUILD_SHARED_LIBS=ON -DBUILD_PORTMIDI_TESTS=OFF"
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release $CMAKE_FLAGS

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        shell: bash
        working-directory: Native/portmidi
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A ${{ matrix.cmake_target_arch }} -DBUILD_SHARED_LIBS=ON -DBUILD_PORTMIDI_TESTS=OFF

      - name: Configure CMake (macOS)
        if: runner.os == 'macOS'
        shell: bash
        working-directory: Native/portmidi
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} -DBUILD_SHARED_LIBS=ON -DBUILD_PORTMIDI_TESTS=OFF

      - name: Build with CMake (Non-ARM Linux)
        if: runner.os == 'Linux' && matrix.arch != 'aarch64' && matrix.arch != 'arm'
        working-directory: Native/portmidi
        run: cmake --build build --config Release --parallel

      - name: Build with CMake (Windows)
        if: runner.os == 'Windows'
        working-directory: Native/portmidi
        run: cmake --build build --config Release --parallel

      - name: Build with CMake (macOS)
        if: runner.os == 'macOS'
        working-directory: Native/portmidi
        run: cmake --build build --config Release --parallel

      - name: Prepare Artifact Directory (Non-ARM)
        if: runner.os != 'Linux' || (runner.os == 'Linux' && matrix.arch != 'aarch64' && matrix.arch != 'arm')
        run: mkdir -p runtimes/${{ matrix.rid }}/native

      - name: Copy Library for Artifact (Non-ARM Linux)
        if: runner.os == 'Linux' && matrix.arch != 'aarch64' && matrix.arch != 'arm'
        shell: bash
        run: |
          cp "Native/portmidi/build/libportmidi.so" "runtimes/${{ matrix.rid }}/native/"

      - name: Copy Library for Artifact
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            cp "Native/portmidi/build/Release/portmidi.dll" "runtimes/${{ matrix.rid }}/native/"
          elif [ "${{ runner.os }}" == "macOS" ]; then
            cp "Native/portmidi/build/libportmidi.dylib" "runtimes/${{ matrix.rid }}/native/"
          fi

      - name: Setup MSVC developer environment (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Analyze Dependencies (Windows)
        if: runner.os == 'Windows' && matrix.arch != 'ARM64'
        run: |
          echo "--- Analyzing Dependencies for ${{ matrix.rid }} ---"
          dumpbin /DEPENDENTS runtimes/${{ matrix.rid }}/native/portmidi.dll

      - name: Analyze Dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          echo "--- Analyzing Dependencies for ${{ matrix.rid }} ---"
          otool -L runtimes/${{ matrix.rid }}/native/libportmidi.dylib

      - name: Analyze Dependencies (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          echo "--- Analyzing Dependencies for ${{ matrix.rid }} ---"
          LIB_PATH="runtimes/${{ matrix.rid }}/native/libportmidi.so"
          if [ "${{ matrix.arch }}" == "x86_64" ]; then
            ldd "$LIB_PATH"
          else
            # ldd doesn't work for cross-compiled binaries, so use readelf
            readelf -d "$LIB_PATH" | grep "NEEDED"
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.rid }}
          path: runtimes/${{ matrix.rid }}

  build-freebsd:
    name: Build for FreeBSD - ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            vm_arch: x86_64
            release: "14.0"
          - arch: arm64
            vm_arch: aarch64
            release: "14.1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build and Prepare Artifact in FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.release }}
          arch: ${{ matrix.vm_arch }}
          usesh: true
          prepare: |
            pkg install -y cmake gmake alsa-lib
          run: |
            set -ex # Exit on error and print commands
            
            # Build the library 
            cd $GITHUB_WORKSPACE/Native/portmidi
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_PORTMIDI_TESTS=OFF
            cmake --build build --config Release --parallel
            
            # Prepare artifact directory and copy the library (inside the VM)
            ARTIFACT_DIR="$GITHUB_WORKSPACE/runtimes/freebsd-${{ matrix.arch }}/native"
            mkdir -p "$ARTIFACT_DIR"
            cp "$GITHUB_WORKSPACE/Native/portmidi/build/libportmidi.so" "$ARTIFACT_DIR/"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: freebsd-${{ matrix.arch }}
          path: runtimes/freebsd-${{ matrix.arch }}

  package:
    name: Package all PortMidi artifacts
    runs-on: ubuntu-latest
    needs: [build, build-freebsd]
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Reorganize and Package
        run: |
          mkdir runtimes
          for dir in artifacts/*; do
            # Get the RID from the directory name (e.g., "win-x64")
            rid=$(basename "$dir")
            echo "Processing artifact for RID: $rid"
          
            target_dir="runtimes/$rid"
            mkdir -p "$target_dir"
            mv "$dir"/* "$target_dir/"
          done
          
          echo "Final package structure:"
          ls -R runtimes
          zip -r portmidi-native-libraries.zip runtimes

      - name: Upload final package
        uses: actions/upload-artifact@v4
        with:
          name: portmidi-native-libraries
          path: portmidi-native-libraries.zip